source 'https://rubygems.org'

gem 'test-kitchen'
gem 'kitchen-ec2', git: 'git://github.com/crowdworks/kitchen-ec2.git', branch: 'fix-regression'
gem 'serverspec'
gem 'chef'
gem 'knife-zero'
gem 'berkshelf'
gem 'aws-sdk'
gem 'knife-solo_data_bag'
gem 'knife-spork'
gem 'rake'
gem 'rspec'
